src/main/java/dao/DeliveryAddressDao.java
src/main/java/dto/DeliveryAddressDto.java

#17 delivery address dao/dto 입니다

---

src/main/java/util/init.sql
src/main/webapp/WEB-INF/web.xml
src/main/webapp/customerReview.jsp

review table 수정

---

src/main/java/util/DbcpBean.java
src/main/webapp/WEB-INF/web.xml

#35 change db name

---

src/main/webapp/include/footer.jsp
src/main/webapp/include/navbar.jsp
src/main/webapp/index.jsp

-footer svg 추가
-navbar font awesome 수정

navbar, footer

---

src/main/java/dao/ReviewDao.java
src/main/java/dto/ReviewDto.java
src/main/java/util/dummy.sql
src/main/webapp/customerReview.jsp
src/main/webapp/protected/review_insert.jsp

dummy review 와 upload 더미 데이터 추가했습니다

dummy spl추가

---

src/main/webapp/seller/productDelete.jsp
src/main/webapp/seller/productList.jsp
src/main/webapp/seller/productUpdate.jsp
src/main/webapp/seller/productUpdate_form.jsp
src/main/webapp/seller/productUpload.jsp
src/main/webapp/seller/productUpload_form.jsp
src/main/webapp/seller/seller.jsp

#59 꼬인 파일들 해결

---

src/main/java/util/dummy.sql

#52 ADD - dummy data about delivery_process and member

---

src/main/java/dao/FileDao.java
src/main/java/dao/ReviewDao.java
src/main/java/dto/FileDto.java
src/main/java/dto/ReviewDto.java

#62 이슈 filedao,dto 변경완료

---

src/main/java/dao/NoticeItemDao.java
src/main/webapp/noticeBoard.jsp

#44 공지사항 작성

---

src/main/java/dao/FileDao.java
src/main/java/dao/ReviewDao.java

dao static 영역 생성자 추가

---

src/main/webapp/WEB-INF/web.xml
src/main/webapp/error/404.jsp
src/main/webapp/error/500.jsp

#65 ADD: error page 404, 500

---

src/main/webapp/include/components/shopblock.jsp
src/main/webapp/myPage.jsp

첫번째 커밋은 myPage.jsp 내용 수정된 것이고,
두번째 커밋은 myPage.jsp 내 뷰포트가 필요가 없어서 제외했습니다.

#39 myPage 수정

---

src/main/webapp/brandstory.jsp

#73 이미지 너비 해결

---

src/main/webapp/include/navbar.jsp

#45  정기배송 페이지 네비게이션 바 링크를 추가했습니다

#45 네비게이션 정기배송 링크 추가

---

src/main/java/util/product_dummy.sql
src/main/java/util/product_option_dummy.sql
src/main/webapp/product/productDetail.jsp
src/main/webapp/product/productList.jsp

#52 ADD - product & product option dummy data 

---

src/main/webapp/noticeBoard.jsp

#90 공지사항 페이지 드롭다운 문제 해결입니다

---

src/main/java/dao/NoticeItemDao.java
src/main/webapp/include/navbar.jsp
src/main/webapp/notice/noticeDetail.jsp
src/main/webapp/notice/noticeList.jsp

#86 공지사항 세부 정보 추가

---

src/main/java/dao/CartItemDao.java
src/main/webapp/cart.jsp
src/main/webapp/cart/cart.jsp
src/main/webapp/cart/cartDelete.jsp
src/main/webapp/product/productList.jsp

cart.jsp, cartDelete.jsp 파일 추가하고 Dao 수정했습니다.

#78 장바구니 작성(부분)

---

src/main/webapp/myPage.jsp

#111 마이페이지 네비게이션바 드롭다운 문제

---

src/main/java/dao/CartItemDao.java
src/main/webapp/cart/cart.jsp
src/main/webapp/cart/cartUpdate.jsp

#78 cart.jsp 에 위 내용 추가하고 dao에 업데이트 추가했습니다.

#78 cart.jsp 업데이트, 옵션변경창 추가

---

src/main/webapp/myPage.jsp

myPage css 수정

---

src/main/java/dao/MemberDao.java

#110 MOD - memberDao for email

---

src/main/java/util/MultipartParser.java
src/main/webapp/review_insert.jsp

#124 멀티파트 파서 작성

---

src/main/webapp/customerReview.jsp
src/main/webapp/include/components/shopblock.jsp
src/main/webapp/myPage.jsp

myPage.jsp css 수정

---

src/main/webapp/include/address.jsp
src/main/webapp/member/protected/delete.jsp
src/main/webapp/member/protected/update.jsp
src/main/webapp/member/protected/update_form.jsp
src/main/webapp/member/signup_form.jsp

MOD - feat:member crud

---

src/main/java/dao/ReviewDao.java
src/main/java/dao/UploadDao.java
src/main/java/dto/ReviewDto.java
src/main/java/dto/UploadDto.java
src/main/java/util/MultipartParser.java
src/main/java/util/init.sql
src/main/webapp/review_insert.jsp
src/main/webapp/review_insertform.jsp

Dao, Dto 새로 추가하고  Upload 테이블 수정했습니다

이미지 업로드 파일 테이블 수정 및 Dao,Dto 추가

---

src/main/java/dao/MemberDao.java

MOD - memberDao insert default value modification

---

src/main/webapp/cart/cart.jsp
src/main/webapp/cart/cartInsert.jsp

#78 cart.jsp 주문 제외 수정하고 cartInsert.jsp 추가했습니다

#78 장바구니(주문 제외 수정)
